runtime: nodejs20
env: standard
service: default

entrypoint: npm start

env_variables:
  MONGO_URI: "mongodb+srv://crm:crm@cluster0.eu4ezjd.mongodb.net/crm"
  ACCESS_TOKEN_SECRET: "htyrtfcdrtfdertfcdrtvcserygbvf"
  REFRESH_TOKEN_SECRET: "iutvdertrdcfrtyhfrtwazswerftf"
  FRONTEND_URL: "https://crmfrontend-dbc12.web.app"
  CLIENT_URL: "https://crmfrontend-dbc12.web.app"
  EMAIL_USER: "crm@refratexindia.net"
  EMAIL_PASS: "nolk qsun sbqy gihd"
  CLOUDINARY_CLOUD_NAME: "dr9o0toid"
  CLOUDINARY_API_KEY: "972484688775781"
  CLOUDINARY_API_SECRET: "dA6Ps7C0XlSOzGpUveuIbd9p6vw"
  EMAIL_CRED_KEY: "sdajbcugducigdebvckhvdvfygqwuy126rr"
